package:
  name: sospex
  version: 0.2.alpha

source:
  git_rev: v0.2-alpha
  git_url: https://github.com/darioflute/fifimon.git

build:
  script:
    -python setup.py install
  
requirements:
  build:
    - python
    - setuptools
    - matplotlib
    - numpy

  run:
    - python
    - numpy
    - astropy >=1.2.1
    - matplotlib
    
test:
  imports:
    - fifimon

about:
  home: https://github.com/darioflute/fifimon
  license: GPL3
  license_file: LICENSE
  description: 'The package monitors FIFI-LS data'
