package:
  name: fifimon
  version: 0.20.alpha

source:
  git_rev: v0.20-alpha
  git_url: https://github.com/darioflute/fifimon.git

build:
  
requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - astropy >=1.2.1
    - matplotlib
    
test:
  imports:
    - fifimon

about:
  home: https://github.com/darioflute/fifimon
  license: GPL3
  license_file: LICENSE
  description: 'The package monitors FIFI-LS data'
