package:
  name: fifimon
  version: 0.4.beta

source:
  git_tag: python3
  git_url: https://github.com/darioflute/fifimon.git

build:
  
requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.12.1
    - astropy >=2.0.2
    - matplotlib >=2.1.0
    
test:
  imports:
    - fifimon

about:
  home: https://github.com/darioflute/fifimon
  license: GPL3
  license_file: LICENSE
  description: 'The package monitors FIFI-LS data'
